name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_HUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}
      run: chmod +x ./scripts/build_and_push.sh && ./scripts/build_and_push.sh
